# GitHub Actions Workflow: Build & Deploy GEN-R-L MiLLz Azure App vv0.3
name: Build and Deploy GEN-R-L MiLLz App vv0.3
on:
  push: { branches: [main] }
  workflow_dispatch:
env:
  ACR_IMAGE_NAME: genrl-millz-image # Consistent image name
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}   # SECRET: e.g., acrgenrlmillz....azurecr.io
        username: ${{ secrets.ACR_USERNAME }}     # SECRET: ACR Admin Username
        password: ${{ secrets.ACR_PASSWORD }}     # SECRET: ACR Admin Password
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      id: build-push
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.ACR_IMAGE_NAME }}:${{ github.sha }} # Tag with git commit SHA
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}            # SECRET: Your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # SECRET: Downloaded from Azure Portal
        images: ${{ steps.build-push.outputs.digest }} # Deploy using the specific image digest
